openapi: 3.0.0
info:
  description: Orchestrator for the Car Rental API flow, based on Java. Main entry point to the Car rental API.
  version: "1.0.0"
  title: Car Rental API
  contact:
    email: marius.moraru@live.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /api/user:
    post:
      callbacks: {}
      deprecated: false
      description: Creates an user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        description: Creates an user
        required: true
      responses:
        '201'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuccessResponse'
        description: CreateResponse
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
      summary: Creates an user
      tags:
        - user
components:
  schemas:
    CreateUserRequest:
      description: Create user details.
      properties:
        id:
          description: User id
          type: string
        email:
          description: User's email
          type: string
        password:
          description: User's password
          type: string
        username:
          description: Username of the user
          type: string
        first_name:
          description: First name of the user
          type: string
        last_name:
          description: Last name of the user
          type: string
        country:
          description: Contry of residence for the user
          type: string
        licese_number:
          description: License number
        status:
          description: User status
          enum:
            - ACTIVE
            - DELETED

